services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: cloud_kitchen
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloud_kitchen_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloud_kitchen
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      RAZORPAY_KEY_ID: ${RP_KEY}
      RAZORPAY_KEY_SECRET: ${RP_SECRET}
    expose:
      - "5000"
    networks:
      - cloud_kitchen_net
    deploy:
      replicas: 3  

  nginx:
    image: nginx:alpine
    container_name: cloud_kitchen_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - cloud_kitchen_net

volumes:
  postgres_data:

networks:
  cloud_kitchen_net:
    driver: bridge
