services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: cloud_kitchen
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud_kitchen_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloud_kitchen
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      RAZORPAY_KEY_ID: ${RP_KEY}
      RAZORPAY_KEY_SECRET: ${RP_SECRET}
    ports:
      - 5000:5000

volumes:
  postgres_data: